# Travis CI instructions

sudo: required
dist: trusty
language: generic

notifications:
  email:
    on_failure: always
    recipients:
      - a.gutenkunst@pilz.de
      - c.henkel@pilz.de
      - h.slusarek@pilz.de
      - i.martini@pilz.de
env:
  global:
    - ROS_DISTRO="melodic"
    - CATKIN_LINT=true
    - CATKIN_PARALLEL_TEST_JOBS="-p1"
    - DOCKER_RUN_OPTS="-e ROSCONSOLE_CONFIG_FILE='/var/rosconsole.config'"
    - BEFORE_SCRIPT='echo $ROSCONSOLE_CONFIG_FILE && echo "log4j.logger.ros.prbt_hardware_support.ServerMock=DEBUG" > $ROSCONSOLE_CONFIG_FILE && cat $ROSCONSOLE_CONFIG_FILE'
  matrix:
    - ROS_REPO=ros
    - ROS_REPO=ros-shadow-fixed
matrix:
  allow_failures:
    - env: ROS_REPO=ros
  fast_finish: true
install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
