language: generic
dist: trusty
os: linux

cache:
  directories:
    - $HOME/.ccache

notifications:
  email:
    on_failure: always
    recipients:
      - a.gutenkunst@pilz.de
      - c.henkel@pilz.de
      - h.slusarek@pilz.de
      - i.martini@pilz.de
env:
  global:
    - ROS_DISTRO="melodic"
    - BUILDER="colcon"
    - CODE_COVERAGE=codecov.io
  matrix:
    - ROS_REPO=main
matrix:
  allow_failures:
    - env: ROS_REPO=main
  fast_finish: true
install:
  - git clone --quiet --depth 1 https://github.com/Briancbn/industrial_ci.git .industrial_ci -b pr-coverage
script:
  - .industrial_ci/travis.sh
  - bash <(curl -s https://codecov.io/bash) -Z
