name: Industrial CI
on: [push]

jobs:
  build:

    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: melodic
        uses: docker://ros:melodic-ros-core
        with:
          entrypoint: /bin/bash
          args: -c "echo $GITHUB_REPOSITORY"
        id: melodic-job